### ISSUE TITLE
In fuckingshellscripts.org, the server config is listed twice

### ISSUE THREAD

**Issue by dannguyen** [brandonhilkert/fucking_shell_scripts#15]
Probably a copy-and-paste mistake, but honestly, had me confused until I noticed the `README.md` was more up to date.

This is currently on README.md:

``` yaml
# servers/search-server.yml
##################################################
# This file defines how to build our search server
##################################################

name: search-server
size: c1.xlarge
availability_zone: us-east-1d
image: ami-90374bf9
key_name: pd-app-server
private_key_path: /Users/yourname/.ssh/pd-app-server
security_groups: search-service  # override the security_groups defined in defaults.yml
```

---

This is what is on [fuckingshellscripts.org](http://fuckingshellscripts.org/), with discrepancy highlighted

``` yaml
# servers/search-server.yml
##################################################
# This file defines how to build our search server
##################################################

## >>>>> This seems to be redundant
security_groups: pd-app-server
instance_type: c1.xlarge
image_id: ami-e76ac58e
## <<<<<<<
availability_zone: us-east-1d
region: us-east-1
key_name: pd-app-server

name: search-server
private_key_path: /Users/yourname/.ssh/pd-app-server
security_groups: search-service  # override the security_groups defined in defaults.yml
instance_type: c1.medium
image_id: ami-90374bf9
```
